[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "py-scriptor"
version = "0.1.0"
description = "Your project description"
authors = [{name = "Your Name", email = "your@email.com"}]
readme = ""
license = {text = "MIT"}
dependencies = []
